import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Techies</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
};

export default Home;
